# Generated by Django 5.0.6 on 2024-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customeraddpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('petname', models.CharField(max_length=20)),
                ('pettype', models.CharField(max_length=10)),
                ('petbreed', models.CharField(max_length=30)),
                ('petcolor', models.CharField(max_length=20)),
                ('petage', models.CharField(max_length=15)),
                ('petgender', models.CharField(max_length=10)),
                ('chooseanimage', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='customerbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.CharField(max_length=20)),
                ('customerusername', models.CharField(max_length=30)),
                ('hhtusername', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customerfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('hhtname', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='customerticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('hhtname', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
            ],
        ),
    ]
