# Generated by Django 5.0.6 on 2024-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='handlerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
